package io.github.chaosunity;

public enum Character {
    COLON,
    TOP_LEFT_CORNER_HARD,
    BOTTOM_LEFT_CORNER_HARD,
    LEFT_CONNECTOR,
    HORIZONTAL_LINE,
    VERTICAL_LINE,
    DOT,
    ANCHOR,
    ANCHOR_HORIZONTAL_LINE,
    ANCHOR_VERTICAL_LINE,
    BOTTOM_LEFT_CORNER_ROUND
}
